version: '3'
services:
  # Application Dockerfile is in same folder which is . the current directory
  app:
    build: .

  # db is is db folder
  db:
    build: world-db/.
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
    - "33060:3306"
