# This YAML file defines a workflow for a Hello World App.
# It triggers the workflow when a push event occurs.

# The name of the workflow
name: A workflow for my Hello World App

# The event that triggers the workflow
on: push

# The jobs to be executed in the workflow
jobs:
  # Job: build
  build:
    # The name of the job
    name: Hello world action

    # The type of runner to use for the job
    runs-on: ubuntu-20.04

    # The steps to be executed in the job
    steps:
      # Step: Checkout
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # Step: Set up JDK 16
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'

      # Step: Build with Maven
      - name: Build with Maven
        run: mvn package
      - name: Build Docker Image
        run: docker build -t semimage .
      - name: Run image
        run: docker run --name semcontainer -d semimage
      - name: view logs
        run: docker logs semcontainer

      # Step: Run docker compose
      - name: Run docker compose
        run: docker-compose up --abort-on-container-exit
