name: World Population Report
on:
  push:

jobs:
  UnitTests:
    name: Unit Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Unit Tests
        run: |
          docker build -t database ./world-db
          docker run --name world -dp 33060:3306 database
          mvn -Dtest=com.Ace.sem.unitTesting test
          docker stop world
          docker rm world
          docker image rm database

  IntegrationTests:
    name: Integration Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Integration Tests
        run: |
          docker build -t database ./world-db
          docker run --name world -dp 33060:3306 database
          mvn -Dtest=com.Ace.sem.IntegratedTest test
          docker stop world
          docker rm world
          docker image rm database
      - name: CodeCov
        uses: codecov/codecov-action@v3
        with:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          directory: ./target/site/jacoco
          flags: Integration Tests # optional
          verbose: true # optional (default = false)

  build:
    name: Build and Start Using docker-compose
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Package and Run docker compose
        run: |
          mvn package -DskipTests
          docker-compose up --abort-on-container-exit
