name: World Population Report
on:
  push:

jobs:
  UnitTests:
    name: Unit Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Unit Tests
        run: mvn -Dtest=com.Ace.sem.unitTesting test

#  IntegrationTests:
#    name: Integration Tests
#    runs-on: ubuntu-20.04
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2
#        with:
#          submodules: recursive
#      - name: Set up JDK 16
#        uses: actions/setup-java@v2
#        with:
#          java-version: '16'
#          distribution: 'adopt'
#      - name: Integration Tests
#        run: |
#          docker build -t database ./world-db
#          docker run --name world -dp 33060:3306 database
#          mvn -Dtest=com.Ace.sem.IntegratedTest test
#          docker stop world
#          docker rm world
#          docker image rm database
name: Integration Tests

on:
  push:
    branches:
      - main

jobs:
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-20.04

    services:
      database:
        image: database # Replace with the appropriate image name for your database
        ports:
          - 33060:3306

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'

      - name: Build Database Docker Image
        run: docker build -t database ./world-db

      - name: Start Database Container
        run: docker run --name worldReport -dp 33060:3306 database

      - name: Run Integration Tests
        run: mvn -Dtest=com.Ace.sem.IntegratedTest test

      - name: Stop Database Container
        run: docker stop worldReport

      - name: Remove Database Container
        run: docker rm worldReport

      - name: Remove Database Docker Image
        run: docker image rm database


  build:
    name: Build and Start Using docker-compose
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Package and Run docker compose
        run: |
          mvn package -DskipTests
          docker-compose up --abort-on-container-exit
